#!/bin/sh
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

if [ "$1" = "upgrade" ] ; then
    # Disable previously used squid3 (now we have squidssl)
    echo '>>> Stopping old squid3 via invoke-rc..'
    invoke-rc.d squid3 stop

    echo '>>> Removing old squid3 via update-rc..'
    update-rc.d squid3 remove

    echo '>>> Removing diversion of squid start/stop script'
    SQUID=/etc/init.d/squid3
    [ -L $SQUID ] && rm $SQUID
    dpkg-divert --remove --package eblocker-baseconfig --rename --divert $SQUID.distrib $SQUID
fi

