#!/bin/sh
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

if [ "$1" = remove ] ; then

 ###  R E D S O C K S  ###
 
# Stop service:
    update-rc.d redsocks remove
    
# Remove diversion of redsocks start/stop script
    REDSOCKS=/etc/init.d/redsocks

    [ -L $REDSOCKS ] && rm $REDSOCKS
    dpkg-divert --remove --package eblocker-baseconfig --rename --divert $REDSOCKS.distrib $REDSOCKS

    update-rc.d redsocks defaults    


 ###  Tor ###
 
# Stop service:
    update-rc.d tor remove
    
# Remove diversion of tor start/stop script
    TOR=/etc/init.d/tor

    [ -L $TOR ] && rm $TOR
    dpkg-divert --remove --package eblocker-baseconfig --rename --divert $TOR.distrib $TOR

    update-rc.d tor defaults

fi

exit 0
