#!/bin/bash
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# Minimal path needed for update-rc.d:
export PATH=/usr/sbin:/usr/bin:/sbin:/bin

CONFDIR=/opt/eblocker-icap/network

CONF_INTERFACES=$CONFDIR/interfaces
CONF_RESOLV=$CONFDIR/resolv.conf

cleanup_ntp_conf_dhcp() {
    # EB1-2296: cleaning up /var/lib/ntp/ntp.conf.dhcp would happen automatically,
    # if "ifdown eth0" was called before /etc/network/interfaces was overwritten
    grep -q 'dhcp' /etc/network/interfaces || rm -f /var/lib/ntp/ntp.conf.dhcp
}

# Install IP configuration (dhcp or static)
if test -f $CONF_INTERFACES
then
    chown root:root $CONF_INTERFACES
    mv $CONF_INTERFACES /etc/network/
    cleanup_ntp_conf_dhcp
fi

# Install nameserver configuration
if test -f $CONF_RESOLV
then
    chown root:root $CONF_RESOLV
    mv $CONF_RESOLV /etc/
fi

# Sync file systems (before user pulls the plug)
sync
