#!/bin/sh
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

CONFDIR=/opt/eblocker-icap/network

# Install firewall configuration
if [ -f $CONFDIR/firewall.conf.delta  ]; then
    iptables-restore -n < $CONFDIR/firewall.conf.delta
elif [ -f $CONFDIR/firewall.conf ]; then
    iptables-restore < $CONFDIR/firewall.conf
fi
