#!/bin/bash
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# Call this script whenever a new CA is generated, see man page of security_file_certgen:
#
#    Certificates are stored in this database in signed form. After any
#    change to the signing CA in squid.conf be sure to erase and
#    re-initialize the certificate database.
#

SQUID_CERT_DB='/var/lib/ssl_db'
SQUID_CERT_DEAMON='/usr/lib/squid/security_file_certgen'

if [ -d $SQUID_CERT_DB ];
then
    rm -r $SQUID_CERT_DB
fi
$SQUID_CERT_DEAMON -c -s $SQUID_CERT_DB -M 4MB
chown -R proxy $SQUID_CERT_DB
