#!/bin/sh
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# Minimal path needed for update-rc.d:
export PATH=/usr/sbin:/usr/bin:/sbin:/bin

# enable DHCP server
update-rc.d isc-dhcp-server defaults # for backwards-compatibility only (previously, dhcpd-disable removed the links)
update-rc.d isc-dhcp-server enable

# Sync file systems (before user pulls the plug)
sync

# and start it if an argument is supplied:
if [ $# -gt 0]
  then
    service isc-dhcp-server start
fi

