#!/bin/bash
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# This script takes the prepared new file for the /etc/iproute2/rt_tables (, which registers the routing tables for the kernel?!)
# and overrides the current /etc/iproute2/rt_tables with the one the Icapserver prepared.
# After that it makes the changes effective, by flushing the ip route cache.

TEMP_RESULT_FILE=/opt/eblocker-icap/network/iproute2.rt_tables.result
DESTINATION=/etc/iproute2/rt_tables

# override the file
cp $TEMP_RESULT_FILE $DESTINATION

# make changes effective
ip route flush cache
