#!/bin/bash
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# This script reports  the openvpn client instance gets killed to openvpnclient
#
#


if [ $# -ge '1' ];
then
	ID=$1
	VPNTABLE_NAME="openvpn$ID"

	# tell OpenVPNController that this VPN client instance is going down
	# and the reason why it is going down ($signal) as third parameter
	redis-cli PUBLISH "vpn_profile_status:$ID:in" "down $signal" > /dev/null

else
	echo "Wrong number of arguments! Expecting the VPN profile ID as first argument!"

fi