#!/bin/bash
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#
# Remove the Root CA + key and the SSL certificate for the Webserver
folder='/opt/eblocker-icap/keys/ssl'

#check if files exist and only if they do delete them individually

if [ -f $folder/eblocker.cert ]
then
    rm $folder/eblocker.cert
fi

if [ -f $folder/eblocker.der.cert ]
then
    rm $folder/eblocker.der.cert
fi

if [ -f $folder/eblocker.key ]
then
    rm $folder/eblocker.key
fi

if [ -f $folder/eblocker.p12.64 ]
then
    rm $folder/eblocker.p12.64
fi
