#!/bin/bash
#
# Copyright 2024 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# Checks whether a previous update attempt failed
# Returns:
# 0: Updates failed
# 1: Updates were successful
# 2: The check failed (probably because there has not been any update attempt yet)

ERROR_TAG=eBlocker_Update_Error
LOG_STDERR=/var/log/eblocker/install-eblocker-updates.errors.log

grep $ERROR_TAG $LOG_STDERR
