#!/bin/bash
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#
#
# This script creates the policy based routing rules. It expects the routing tables to be already registered and named with a common prefix.
#
# Usage:
#   openvpn_policy [-4|-6] prefix offset [id...]
# where
#   prefix is the routing table prefix (e.g. openvpn)
#   offset each rule is given a priority of offset + id
#

if [ $# -ge '3' ];
then
    # Policy Routing Rules:
    # add policy routing rules
    IP_VERSION=$1
    TABLE_NAME_PREFIX=$2
    OFFSET=$3

    # clear all previously set rules
    for rule in `ip $IP_VERSION rule | sed -n 's/^\([0-9]\+\):.*openvpn[0-9]\+/\1/p'`; do
        ip $IP_VERSION rule del pref $rule
    done

    shift 3
    while(("$#")); do
        ip $IP_VERSION rule add prio $(($OFFSET+$1)) from all fwmark $1 table $TABLE_NAME_PREFIX$1
        shift
    done

    # cleanup,commit changes
    ip $IP_VERSION route flush cache
else
    echo "Wrong number of arguments!" 1>&2
    exit 1
fi
