#!/bin/bash
#
# Copyright 2026 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# Format: wireguard_clearclientroute [ID] [ENDPOINT_IP]

if [ $# -ge '2' ]; then
    ID=$1
    endpoint_ip=$2

    ip route del "$endpoint_ip/32" || true
else
    echo "Wrong number of arguments! Expected: wireguard_clearclientroute [ID] [ENDPOINT_IP]" 1>&2
    exit 1
fi
