#!/bin/bash
#
# Copyright 2026 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# Format: wireguard_clearclientroute [ID]

if [ $# -ge '1' ]; then
    ID=$1

    VPNTABLE_NAME="wireguard$ID"

    ip route show table $VPNTABLE_NAME default > /dev/null || true
    ip route del table $VPNTABLE_NAME default || true
    ip -6 route show table $VPNTABLE_NAME default > /dev/null || true
    ip -6 route del table $VPNTABLE_NAME default || true
    ip route flush cache
    ip -6 route flush cache
else
    echo "Wrong number of arguments! Expected: wireguard_clearclientroute [ID]" 1>&2
    exit 1
fi
