#!/bin/bash
#
# Copyright 2026 eBlocker Open Source GmbH
# Licensed under the EUPL, Version 1.2 or later.
#
# Format: wireguard_mobile_start [CONFIG_FILE]

set -e

if [ $# != '1' ]; then
    echo "Error: Wrong number of parameters!" 1>&2
    echo "Expected format: wireguard_mobile_start [CONFIG_FILE]" 1>&2
    exit 1
fi

CONFFILE=$1
IFACENAME=$(basename "$CONFFILE" .conf)

if [ ! -f "$CONFFILE" ]; then
    echo "The config file can not be found here: $CONFFILE" 1>&2
    exit 1
fi

wg-quick up "$CONFFILE"

OUT_IF=$(ip route show default | awk '{print $5; exit}')
VPN_NET=$(ip -4 route show dev "$IFACENAME" proto kernel scope link | awk '{print $1; exit}')
DNS_SERVER=$(ip -4 address show dev "$IFACENAME" | awk '/inet / { split($2, a, "/"); print a[1]; exit }')

iptables -C FORWARD -i "$IFACENAME" -o "$OUT_IF" -j ACCEPT 2>/dev/null || \
    iptables -A FORWARD -i "$IFACENAME" -o "$OUT_IF" -j ACCEPT
iptables -C FORWARD -i "$OUT_IF" -o "$IFACENAME" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || \
    iptables -A FORWARD -i "$OUT_IF" -o "$IFACENAME" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -t nat -C POSTROUTING -s "$VPN_NET" -o "$OUT_IF" -j MASQUERADE 2>/dev/null || \
    iptables -t nat -A POSTROUTING -s "$VPN_NET" -o "$OUT_IF" -j MASQUERADE
iptables -t nat -C PREROUTING -i "$IFACENAME" -p udp --dport 53 -j DNAT --to-destination "$DNS_SERVER:5300" 2>/dev/null || \
    iptables -t nat -A PREROUTING -i "$IFACENAME" -p udp --dport 53 -j DNAT --to-destination "$DNS_SERVER:5300"
iptables -t nat -C PREROUTING -i "$IFACENAME" -p tcp --dport 53 -j DNAT --to-destination "$DNS_SERVER:5300" 2>/dev/null || \
    iptables -t nat -A PREROUTING -i "$IFACENAME" -p tcp --dport 53 -j DNAT --to-destination "$DNS_SERVER:5300"
