#!/bin/bash
#
# Copyright 2026 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# Format: wireguard_setclientroute [ID] [IFACENAME] [NORMAL_GATEWAY] [ENDPOINT_IP]
# Adds the provider endpoint route via the normal gateway and the VPN policy
# table default route via the WireGuard interface.

if [ $# -ge '4' ]; then
    ID=$1
    IFACENAME=$2
    route_net_gateway=$3
    endpoint_ip=$4

    VPNTABLE_NAME="wireguard$ID"

    ip route add "$endpoint_ip/32" via $route_net_gateway || true

    if ip route show table $VPNTABLE_NAME default | grep -qs 'default'; then
        ip route del table $VPNTABLE_NAME default
    fi
    ip route add table $VPNTABLE_NAME default dev $IFACENAME

    ip route flush cache
else
    echo "Wrong number of arguments! Expected: wireguard_setclientroute [ID] [IFACENAME] [NORMAL_GATEWAY] [ENDPOINT_IP]" 1>&2
    exit 1
fi
