#!/bin/bash
#
# Copyright 2026 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# Format: wireguard_start [ID_OF_INSTANCE] [CONFIG_FILE] [LOG_FILE]
# Starts a WireGuard provider profile via wg-quick. Runtime configs are
# generated with "Table = off" so eBlocker policy routing remains in control.

if [ $# == '3' ]; then
    ID=$1
    CONFFILE=$2
    LOGFILE=$3
    IFACENAME=$(basename "$CONFFILE" .conf)

    if [ -f "$CONFFILE" ]; then
        if wg-quick up "$CONFFILE" >> "$LOGFILE" 2>&1; then
            redis-cli PUBLISH "vpn_profile_status:$ID:in" "up $IFACENAME"
        else
            redis-cli PUBLISH "vpn_profile_status:$ID:in" "down wg-quick-failed"
            exit 1
        fi
    else
        echo "The config file can not be found here: $CONFFILE" 1>&2
        exit 1
    fi
else
    echo "Error: Wrong number of parameters!" 1>&2
    echo "Expected format: wireguard_start [ID_OF_INSTANCE] [CONFIG_FILE] [LOG_FILE]" 1>&2
    exit 1
fi
