#!/bin/sh
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

remove_dhcp_defaults_diversion() {
    # Remove diversion of defaults for isc-dhcp-server
    local DHCP_DEFAULTS=/etc/default/isc-dhcp-server

    [ -L $DHCP_DEFAULTS ] && rm $DHCP_DEFAULTS
    dpkg-divert --remove --package eblocker-icapserver --rename --divert $DHCP_DEFAULTS.distrib $DHCP_DEFAULTS
}

if [ "$1" = remove ] ; then

    remove_dhcp_defaults_diversion

# Stop services:
    invoke-rc.d icapserver stop

fi

exit 0
